[project]
name = "litestar-forms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "msgspec>=0.19.0",
    "pydantic>=2.11.2",
]

[dependency-groups]
dev = [
    "litestar[standard]>=2.15.2",
]
